### ISSUE TITLE
(*Iter).MapScan fails on tuples in Cassandra 2.2.4

### ISSUE THREAD

**Issue by kristoiv** [gocql/gocql#561]
The program panics on the first call to MapScan() due to being unable to reflect.New(nil). Debugging suggests it consideres the TupleType as custom, as the func "getApacheCassandraType(class string) (Type)" receives "org.apache.cassandra.db.marshal.TupleType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.Int32Type)" in its "class" argument.

The method continues to strips it down to: 
"TupleType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.Int32Type)" before comparing it to every type, including "TupleType" in a switch statement. But the tuple-contents prevents it from recognizing it. Thus we end up with a panic when the type is custom (=0x00 / nil).

The following is a code example reproducing the error, I appreciate any help on this matter:
``` go
package main

import (
	"fmt"
	"log"

	"github.com/gocql/gocql"
)

func main() {
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Consistency = gocql.One

	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatalln(err)
	}

    // Create testing keyspace
    if err := session.Query(`CREATE KEYSPACE IF NOT EXISTS gocqldebugging_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Create table with tuple in it
    if err := session.Query(`CREATE TABLE IF NOT EXISTS gocqldebugging_test.test (id uuid PRIMARY KEY, myNonCustom frozen<tuple<int, int>>);`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Insert some data into our table
    if err := session.Query(`INSERT INTO gocqldebugging_test.test (id, myNonCustom) VALUES (uuid(), (1, 2));`).Exec(); err != nil {
        log.Fatalln(err)
    }

    fmt.Println("Results:")
	var m map[string]interface{}
	iter := session.Query(`SELECT * FROM gocqldebugging_test.test`).Iter()
	for iter.MapScan(m) {
		fmt.Printf("%T: %#v\n", m, m)
	}

	fmt.Println("Done.")
}

```

And the panic message (brief; test to see full):

```bash
panic: reflect: New(nil)

goroutine 1 [running]:
reflect.New(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.2/libexec/src/reflect/value.go:2113 +0x85
```

**Comment by Zariel** [comment]
@kristoiv Thank you for the report and test case, this should now be fixed.

**Comment by kristoiv** [comment]
@Zariel Thanks for fixing this so quickly. I will try my more complicated use case right away :)

**Comment by kristoiv** [comment]
@Zariel Did you test with my exact use case? It still wont compile on my side. I started by doing "go get -u github.com/gocql/gocql", then I double checked that the git-repo was in-fact up to date (confirming the your commits were in the git log; did a forceful checkout of master again). I did "go clean". Still not working. So I manually deleted the whole $GOPATH/pkg/arch/github.com/gocql.

I'm still having trouble. Any suggestions?

**Comment by Zariel** [comment]
You need to allocate the map passed into MapScan

**Comment by kristoiv** [comment]
@Zariel That is a very good point, but the panic is the same as before, and this happens earlier in the lib. I tried to change it to the following and it still fails:

```go
(...)

fmt.Println("Results:")
m := make(map[string]interface{})
iter := session.Query(`SELECT * FROM gocqldebugging_test.test`).Iter()
for iter.MapScan(m) {
    fmt.Printf("%T: %#v\n", m, m)
}
fmt.Println("Done.")
```

**Comment by Zariel** [comment]
When I run this,

```go
package main

import (
    "fmt"
    "log"

    "github.com/gocql/gocql"
)

func main() {
    cluster := gocql.NewCluster("127.0.0.1")
    cluster.Consistency = gocql.One
	cluster.ProtoVersion = 4

    session, err := cluster.CreateSession()
    if err != nil {
        log.Fatalln(err)
    }

    // Create testing keyspace
    if err := session.Query(`CREATE KEYSPACE IF NOT EXISTS gocqldebugging_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Create table with tuple in it
    if err := session.Query(`CREATE TABLE IF NOT EXISTS gocqldebugging_test.test (id uuid PRIMARY KEY, myNonCustom frozen<tuple<int, int>>);`).Exec(); err != nil {
        log.Fatalln(err)
    }

    // Insert some data into our table
    if err := session.Query(`INSERT INTO gocqldebugging_test.test (id, myNonCustom) VALUES (uuid(), (1, 2));`).Exec(); err != nil {
        log.Fatalln(err)
    }

    fmt.Println("Results:")
    var m map[string]interface{} = make(map[string]interface{})
    iter := session.Query(`SELECT * FROM gocqldebugging_test.test`).Iter()
    for iter.MapScan(m) {
        fmt.Printf("%T: %#v\n", m, m)
    }

    fmt.Println("Done.")
}
```

I get this

```
Results:
map[string]interface {}: map[string]interface {}{"id":gocql.UUID{0xdf, 0xcc, 0x4d, 0x7f, 0x89, 0x2a, 0x4b, 0x9d, 0x87, 0x15, 0xcd, 0x2f, 0x97, 0xc1, 0xb6, 0xcc}, "mynoncustom[0]":1, "mynoncustom[1]":2}
Done.
```

**Comment by kristoiv** [comment]
Ah! There you go, I was missing "cluster.ProtoVersion = 4". I guess I have to look into that ;).
Thanks again!

**Comment by kristoiv** [comment]
@Zariel I tried my more advanced nested case (with a map), and it didn't work out all that well (see the attached code). Is there a better, sane'er way of doing this?

Thanks for fixing the base case :+1: 

```go
package main

import (
	"fmt"
	"log"

	"github.com/gocql/gocql"
)

func main() {
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Consistency = gocql.One
	cluster.ProtoVersion = 4

	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatalln(err)
	}

	// Drop testing keyspace
	if err := session.Query(`DROP KEYSPACE gocqldebugging_test;`).Exec(); err != nil {
		log.Fatalln(err)
	}

	// Create testing keyspace
	if err := session.Query(`CREATE KEYSPACE gocqldebugging_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};`).Exec(); err != nil {
		log.Fatalln(err)
	}

	// Create table with tuple in it
	if err := session.Query(`CREATE TABLE gocqldebugging_test.test (id uuid PRIMARY KEY, myNonCustom map<uuid,frozen<tuple<int, int>>>);`).Exec(); err != nil {
		log.Fatalln(err)
	}

	// Insert some data into our table
	if err := session.Query(`INSERT INTO gocqldebugging_test.test (id, myNonCustom) VALUES (uuid(), {uuid():(1, 2),uuid():(3,4)});`).Exec(); err != nil {
		log.Fatalln(err)
	}

	m := make(map[string]interface{})
	iter := session.Query(`SELECT * FROM gocqldebugging_test.test`).Iter()
	fmt.Printf("%[1]T: %#[1]v\n", iter.MapScan(m))
	fmt.Printf("%T: %#v\n", m, m)
}
```

**Comment by Zariel** [comment]
In what way? I would personally use `Scan` and not use `MapScan`, also if you only get one row you can call `Scan` or `MapScan` on the query directly, also make sure to check the error from `iter.Close`

**Comment by kristoiv** [comment]
Ah, great tip. Err was: "cannot unmarshal tuple into *[]interface {}".
I'm using MapScan because it is a generic ORM like tool (gocqltable). Scan is difficult too, get the same error if I do this:

```go
package main

import (
	"fmt"
	"log"

	"github.com/gocql/gocql"
)

func main() {
	cluster := gocql.NewCluster("127.0.0.1")
	cluster.Consistency = gocql.One
	cluster.ProtoVersion = 4

	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatalln(err)
	}

	// Drop testing keyspace
	if err := session.Query(`DROP KEYSPACE gocqldebugging_test;`).Exec(); err != nil {
		log.Fatalln(err)
	}

	// Create testing keyspace
	if err := session.Query(`CREATE KEYSPACE gocqldebugging_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};`).Exec(); err != nil {
		log.Fatalln(err)
	}

	// Create table with tuple in it
	if err := session.Query(`CREATE TABLE gocqldebugging_test.test (id uuid PRIMARY KEY, myNonCustom map<uuid,frozen<tuple<int, int>>>);`).Exec(); err != nil {
		log.Fatalln(err)
	}

	// Insert some data into our table
	if err := session.Query(`INSERT INTO gocqldebugging_test.test (id, myNonCustom) VALUES (uuid(), {uuid():(1, 2),uuid():(3,4)});`).Exec(); err != nil {
		log.Fatalln(err)
	}

	var id gocql.UUID
	m := make(map[gocql.UUID][]interface{})
	if err := session.Query(`select id, myNonCustom from gocqldebugging_test.test`).Scan(&id, &m); err != nil {
		log.Fatalln(err)
	}

	fmt.Println(id, m)
}

```

**Comment by kristoiv** [comment]
@Zariel Should I repost this as an open issue?

**Comment by Zariel** [comment]
That would be best, im not sure how best to handle tuples in this case, as we currently handle them as follows.

The tuple is returned from cassandra as a single column, we expand the column, providing 1 column per element in the tuple, this makes it easy to scan and unmarshal. It is not possible to scan a tuple into a []interface because it is not one column, it is some number of elements.
