### ISSUE TITLE
deadlock encountered in gocql.. stuck connections?

### ISSUE THREAD

**Issue by Dieterbe** [gocql/gocql#664]
hello,
we recently encountered a deadlock issue in production.  It looks like gocql got stuck on some locks.
I haven't been able to undestand the gocql code fully yet, so hopefully we can figure this out better and fix the problem.
the original ticket on our end lives at https://github.com/raintank/raintank-metric/issues/159
What you should know about our service is that it uses [cassandra and gocql](https://github.com/raintank/raintank-metric/blob/master/metric_tank/store_cassandra.go), it writes <1kB chunks of data to cassandra (it has a write queue which is filled every 10 min and usually drained within 90 seconds) and it also serves read requests by fetching chunks and serving the data.
we run with 5 gocql connections that are used for both saving data as well as satisfying reads.
we recently introduced a change that increases the reads parrallelism, and once we rolled it out, we saw that after serving some reads the writes of new chunks weren't happening anymore.
there's a log at https://github.com/raintank/raintank-metric/issues/159#issuecomment-189006659 I turned on writes at 20:39, the writes at 20:40 almost all completed, most of the extra chunks at 20:50 seemed to work fine, but some remained in the queue, and afterwards not a single chunk got saved.
(you can see this visually at https://snapshot.raintank.io/dashboard/snapshot/OKf5ClRD5TO9NpYGL5sGRxORjSw8t9Cu , bottom row and middle graph of second-to last row)
in the log the first errors are "2016/02/25 20:50:21 [store_cassandra.go:282 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period"
but to be clear: cassandra was working fine, at least all the reads wore completing succesfully within milliseconds (can also be seen on the dashboard)

i also obtained a stacktrace, see 
https://gist.github.com/Dieterbe/0571e313eeb9b2eeab1c (and btw I can recommend https://github.com/maruel/panicparse to present the stacktrace is more concise, understandable manner). the stacktrace was obtained at 21:35 UTC, so about 55min after enabling writes. note how at time of stacktrace, a lot of routines had been stuck for 44 minutes, so since around the 20:50 UTC mark where the 2nd batch of chunks came in.

hopefully we can figure this out,
let me know what else i can do to.
thank you.

**Comment by Zariel** [comment]
Thanks for the report ill take a look.

**Comment by Zariel** [comment]
It looks like the select at https://github.com/gocql/gocql/blob/1a3b806af5e13f64a5da07f1d1cefb53b78c7a4f/conn.go#L344 never unblock so that read lock is held indefinitely.

**Comment by Zariel** [comment]
I think I can reproduce this, will put up a fix soon

**Comment by Zariel** [comment]
@Dieterbe this should be fixed by #665 which is now in master, could you give it a go and let me know if you still observe the issue?

**Comment by Dieterbe** [comment]
@Zariel thanks for the quick action. i'm working on getting a test setup running where i can reliably reproduce the timouts, i'll let you know.

**Comment by Dieterbe** [comment]
@Zariel any tips on how i can bring cassandra/my network in a state that should let me reliable reproduce the issue? 
i've tried slowing down the network bandwidth
```
sudo tc qdisc add dev $iface root tbf rate 100kbit burst 120kbit latency 10ms peakrate 120kbit minburst 1540
```
and also introducing delays
```
sudo tc qdisc add dev $iface root netem delay 1000ms 100ms distribution normal
```

but haven't been able to trigger the deadlock state yet.

**Comment by Zariel** [comment]
I managed to reproduce it by closing the socket after setup, it should be possible to do it by kill 9 Cassandra?

**Comment by Zariel** [comment]
@Dieterbe something to try would be to create a session with 1 connection per host, use a single node cluster, in a loop send select queries, then `SIGSTOP` Cassandra, it should cause writes to start timing out which will trigger the issue.

**Comment by Dieterbe** [comment]
i've been running tests, slamming our service with large-range requests and have verified that after spitting out errors like..
```
/03/06 23:41:53 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:53 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:53 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: too many query timeouts on the connection
2016/03/06 23:41:55 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: too many query timeouts on the connection
2016/03/06 23:41:55 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:55 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:55 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:56 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:56 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
2016/03/06 23:41:58 [store_cassandra.go:293 Search()] [E] cassandra query error. gocql: no response received from cassandra within timeout period
```
...when i take away the load, it resumes working fine again (pulling data from cassandra is super fast again, requests served properly, etc)

**Comment by woodsaj** [comment]
i am a colleague of Deiterbe, and we experienced the deadlock again today on our production cluster.

I have been reading over the code and a stacktrace taken ( https://gist.github.com/woodsaj/ff80f763d7978106f05d ) and i think i may have found the cause of the problem.

there is a race condition when a timeout occurs and a successfull response is received at the same time.

https://github.com/gocql/gocql/blob/master/conn.go
```
 571     select {
 572     case err := <-call.resp:
 573         if err != nil {
 574             if !c.Closed() {
 575                 // if the connection is closed then we cant release the stream,
 576                 // this is because the request is still outstanding and we have
 577                 // been handed another error from another stream which caused the
 578                 // connection to close.
 579                 c.releaseStream(stream)
 580             }
 581             return nil, err
 582         }
 583     case <-timeoutCh:
 584         close(call.timeout)
 585         c.handleTimeout()
 586         return nil, ErrTimeoutNoResponse
 587     case <-c.quit:
 588         return nil, ErrConnectionClosed
 589     }
 590 
 591     // dont release the stream if detect a timeout as another request can reuse
 592     // that stream and get a response for the old request, which we have no
 593     // easy way of detecting.
 594     //
 595     // Ensure that the stream is not released if there are potentially outstanding
 596     // requests on the stream to prevent nil pointer dereferences in recv().
 597     defer c.releaseStream(stream)
```

if a timeout occurs, c.handleTimeout() is called which will then call c.closeWithError(), which then acquires c.mu.RLock().  
however, if another call completes at the same time, a nil error is read from the call.resp channel and c.releaseStream() will be called which acquires c.mu.Lock()

The deadlock occurs when c.closeWithError() acquires the lock after the nil error has been read from call.resp but before c.releaseStream() has run. 

c.closeWithError() will then try to send an error on the call.resp channel or wait for call.timeout to be closed.  call.resp is unbuffered and as execution has already passed through the "select" block there is no goroutine reading from it.  Also, as the block is complete call.timer sending on timeoutCh is also ignored so call.timeout is never closed.

I think this can simply be resolved by calling `close(call.timeout)` on line 573 after a response has been read from the call.resp channel.

**Comment by base698** [comment]
what version is this fixed in?

**Comment by Zariel** [comment]
https://github.com/gocql/gocql/pull/672/commits/a4051028e53fdf9bfb04dc1530d4742deb96e33e

**Comment by clanstyles** [comment]
I'm still having this error. I checked the previous commit and I do see it in my version I compiled with.
